### PR TITLE
optimizations: group JSX options, conditionally assign JSX options vi…

### PR DESCRIPTION
**Pull request by yuens1002**
new to solid, my attempt to optimize existing code to get a better feel for the current code base.

### CODE REVIEW

**Comment by yuens1002** [comment]
not sure what the issues are the expectations are mathing except in the import statements where "r-" is added.

**Comment by yuens1002** [comment]
ran npm run test locally against untouched master, tests fails for this same file.  perhaps something is going on with the test cases?

**Comment by ryansolid** [comment]
It's possible.. I've been upending stuff.. I think the babel plugin is getting cached. I will check it out tonight.

**Comment by ryansolid** [comment]
Yeah it was just two small typos that lead to the vars never being assigned. So while it didn't crash the vars were always the default. Fixed now.

**Pull request merged**
