### PR TITLE
Fix reconcileArrays assuming non-empty input array

### PR DESCRIPTION
**Pull request by EricNRodriguez**

### CODE REVIEW

**Comment by ryansolid** [comment]
Is there a place where you hit this as a bug?

**Comment by EricNRodriguez** [comment]
I was using it directly in a side project and came across it, thought I would correct it whilst I was here. I didn't find any cases where it caused a crash elsewhere, but I also didn't look extensively

**Comment by ryansolid** [comment]
Ok the reason I asked is mostly it is a hot path and if it isn't neccessary Id skip. Plus we don't transpile and there are envs that don't support optional chaining so we'd need to make a slightly larger fix. Unless there is a bug/code path where this causes an issue Id be tempted to leave as is

**Comment by EricNRodriguez** [comment]
Makes sense - I have no strong opinions so I'll close this off given the above info. Thanks Ryan

**Pull request closed without merging**
